#!/bin/sh

# SPDX-PackageName: vnc-image-docker
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://github.com/rfinnie/vnc-image-docker
# SPDX-FileCopyrightText: © 2025 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0

set -e

RES="$(/srv/vnc-image/extract-image)"
exec x11vnc -rawfb "file:/tmp/image.raw@${RES}x32:ff/ff00/ff0000" -forever -shared -rfbport 5900
