# SPDX-PackageSummary: vnc-image-docker
# SPDX-FileCopyrightText: © 2025 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0
---
name: "Build and push registry"
"on":
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions: "write-all"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Log in to registry"
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: "Build image"
        run: "docker image build -t build:ci ."
      - name: "Push image"
        run: |
          docker image tag build:ci ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          docker image push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
